name: build-image-push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Pproduction -DskipTests --file pom.xml

  build-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag team-tally

  login-to-docker-hub:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
  push-image:
    needs: login-to-docker-hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: Push Docker image
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/teamtally
      
